### ISSUE TITLE
Bug - Pi Pico

### ISSUE THREAD

**Issue by mynameistakenhowcanthatb** [Octal450/J-Runner-with-Extras#12] opened 2022-02-22 23:52 UTC
jasper works 100% read and write 
falcon get a error saying  PicoFlasher firmware is too old so cant read it .

![pico](https://user-images.githubusercontent.com/28812845/155238840-f251a280-7303-403d-8205-cb4b316dfbb9.jpg)

**Comment by mynameistakenhowcanthatb** [comment] 2022-02-23 00:03
if i keep trying get this 
System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   at JRunner.PicoFlasher.RecvUInt32(SerialPort serial)
   at JRunner.PicoFlasher.<>c__DisplayClass20_0.<ReadNand>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by nikdiklic** [comment] 2022-02-23 00:13
Download the new version of the PicoFlasher firmware ([PicoFlasher.uf2](https://github.com/X360Tools/PicoFlasher/releases/download/2.0/PicoFlasher.uf2))

**Comment by Octal450** [comment] 2022-02-23 00:39
Some of the bugs have been fixed by balika and will be available in the new version. I will try to reproduce this with the latest firmware.
J

**Comment by Octal450** [comment] 2022-02-24 19:53
Can't reproduce on the latest version, so assuming its one of the things balika already fixed.

Try building from next and if it still happens, re-open the issue.

Kind Regards,
Josh

**Closed by Octal450** 2022-02-24 19:53 UTC
