### ISSUE TITLE
Bug - JRunner UI crashes

### ISSUE THREAD

**Issue by ElecTriX666** [Octal450/J-Runner-with-Extras#56] opened 2024-05-10 17:09 UTC
**Describe the bug**
UI crashes when trying to create XeBuild with selected drives patches and "other patches".

If skipping drive patches and other patches build works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load source file (nand.bin)
2. Select kernel 17559, Glitch2, RGH3 25mhz
3. Go to tab "Patches" and select "Both XL", "UsbdSec" and "Key fix"
4. UI takes a second then force closes

**Expected behaviour**
A build is done?

**Screenshots**
![image](https://github.com/Octal450/J-Runner-with-Extras/assets/35463138/e24b0586-f4e3-47d3-b657-dc23ca9f24a5)
![image](https://github.com/Octal450/J-Runner-with-Extras/assets/35463138/57a0f062-0969-420f-9fb8-4f1d7cf68cee)

**System (please complete the following information):**
 - OS: Windows
 - Version: 11 Pro

**Additional context**
Error.log;
> System.IO.IOException: Det går inte att skapa en fil som redan finns.
>    vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    vid System.IO.__Error.WinIOError()
>    vid System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
>    vid JRunner.Classes.xebuild.copyXLBoth()
>    vid JRunner.Classes.xebuild.createxebuild(Boolean custom)
>    vid JRunner.Panels.XeBuildPanel.createxebuild_v2(Boolean custom, PrivateN nand, Boolean fullDataClean)
>    vid JRunner.MainForm.<btnXeBuildClick>b__186_0()
>    vid System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    vid System.Threading.ThreadHelper.ThreadStart()

**Comment by Octal450** [comment] 2024-05-10 18:09
This error it sounds like Windows Defender sandboxing. Please add exception to the app. As such I cannot reproduce it.

I will see if I can handle that gracefully and warn the user.

Kind Regards,
Josh

**Comment by ElecTriX666** [comment] 2024-05-11 17:48
> This error it sounds like Windows Defender sandboxing. Please add exception to the app. As such I cannot reproduce it.
> 
> I will see if I can handle that gracefully and warn the user.
> 
> Kind Regards, Josh

Hi,

Sorry but Defender is not activated and no other antivirus is installed.

System.IO.IOException: Det går inte att skapa en fil som redan finns.
translation
System.IO.IOException: Can not create a file that already exists.

This error shows even with a clean unpacked Jrunner. With no created folders

**Comment by ElecTriX666** [comment] 2024-05-12 17:35
@Octal450

**Comment by Octal450** [comment] 2024-05-12 22:10
Reproduced.

Working on a fix.

Kind Regards,
Josh

**Comment by Octal450** [comment] 2024-05-12 22:11
It occurs if a build fails and then you try to rebuild. Files are left in an invalid state.
If you use restore files option from hamburger menu it'll fix it.

**Comment by Octal450** [comment] 2024-05-12 22:35
This *should* be fixed in dev/next.

Anyone encountering can use restore files option to fix it on release.

-J

**Closed as completed by Octal450** 2024-05-12 22:35 UTC
Labels: bug, release
